### PR TITLE
Add Dockerfile example to README

### PR DESCRIPTION
**Pull request by renatillas**
Here I've added to the README a Dockerfile example with the necessary code to dockerize a wisp application.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Thank you, but this is not the right place for this. The deployment section of the Gleam website would be a good place for contributions, and in future Wisp will have a website too.

**Comment by renatillas** [comment]
Sorry, I should have linked the issue I saw: https://github.com/gleam-wisp/wisp/issues/16. As it was in this repository, I created the PR here, although I did not know if I should have put it in a separate Dockerfile or in the README.

**Comment by lpil** [comment]
Oh! Sorry! I honestly can't remember what I had in mind when I wrote that ticket. I wish I added a description!

**Comment by lpil** [comment]
Thank you

**Pull request closed without merging**
